name: Build
on:
  push: {}

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:

    - uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::414064234042:role/gha-deployer
        role-session-name: gha-run-${{ github.run_id }}
        aws-region: eu-west-1

    - uses: meteorengineer/setup-meteor@v2
      with:
        meteor-release: '2.15'

    - uses: actions/checkout@v4

    - name: Install NPM dependencies
      run: meteor npm install

    - name: Select temp directory
      id: tempdir
      run: echo "path=$(mktemp -d)" >> "$GITHUB_OUTPUT"

    - name: Build app bundles
      run: meteor build --directory ${{ steps.tempdir.outputs.path }} #--platforms web.browser

    - name: Create manifest
      working-directory: ${{ steps.tempdir.outputs.path }}/bundle/programs
      run: >
        echo '{"web.browser":{"hashes":{"js":"'$(basename web.browser/*.js .js)'","css":"'$(basename web.browser/*.css .css)'"},"html":'$(jq -cn --rawfile body web.browser/body.html --rawfile head web.browser/head.html '$ARGS.named')'},"server":'$(jq -c . < server/config.json)'}' | tee manifest.json | jq .

    - name: Upload manifest to S3
      working-directory: ${{ steps.tempdir.outputs.path }}/bundle/programs
      run: |
        buildPrefix=uber.danopia.net/meteor-bundles/last-done/${{ github.sha }}
        aws s3 cp --content-type "application/json; charset=utf-8" \
          manifest.json s3://$buildPrefix/manifest.json
        echo https://$buildPrefix/manifest.json

    - name: Upload web.browser bundle to S3
      working-directory: ${{ steps.tempdir.outputs.path }}/bundle/programs/web.browser
      run: |
        ls -lsh
        buildPrefix=uber.danopia.net/meteor-bundles/last-done/${{ github.sha }}/web.browser
        aws s3 cp --content-type "application/javascript; charset=utf-8" \
          *.js s3://$buildPrefix/app.js
        aws s3 cp --content-type "text/css; charset=utf-8" \
          *.css s3://$buildPrefix/app.css
        echo https://$buildPrefix/app.js
        echo https://$buildPrefix/app.css
